apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: abcdef.0123456789abcdef
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${host}
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: ${name}
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
---
apiServer:
  certSANs:
  %{~ for host in split(",",hosts)  ~}
    - ${host}
  %{~ endfor ~}
  extraArgs:
    apiserver-count: "${count}"
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: ${name}:6443
controllerManager: {}
dns: {}
etcd:
  external:
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    endpoints: 
    %{~ for addr in split(",",ip_addrs)  ~}
      - ${addr}
    %{~ endfor ~}
    keyFile: /etc/etcd/kubernetes-key.pem
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.24.3
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
